name: stream_games
description: Flutter app for purchasing and renting games.

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.1.2
  fluttertoast: ^4.0.1
  sqflite: any
  video_player: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.17.1 <2.0.0"